---
version: "3"

services:
  postgres:
    image: docker.io/library/postgres:14
    container_name: postgres
    # network_mode: host
    volumes: 
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=assignment
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=assignment
    networks: [ "assignment" ]

  zookeeper:
    image: quay.io/strimzi/kafka:0.36.1-kafka-3.4.1
    container_name: zookeeper
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks: [ "assignment" ]

  kafka:
    image: quay.io/strimzi/kafka:0.36.1-kafka-3.4.1
    container_name: kafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks: [ "assignment" ]

networks:
  assignment:
    name: assignment
